
/*登录功能 */
export const USER_LOGIN_REQUEST = 'PRO/USER_LOGIN_REQUEST';
export const USER_LOGIN_FAILURE = 'PRO/USER_LOGIN_FAILURE';
export const USER_LOGIN_SUCCESS = 'PRO/USER_LOGIN_SUCCESS';
//载入条
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADING_REQUEST = 'USER_LOADING_REQUEST'
    
